// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "preact/jsx-runtime";

function Main(props) {
  return JsxRuntime.jsx("div", {
              children: "Hello World"
            });
}

var make = Main;

export {
  make ,
}
/* preact/jsx-runtime Not a pure module */
